//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moneyshowertech.PL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moneyshowertech.PL.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyShowerTech A.Ş. Bir İTÜ Arı Teknokent ve Boğaziçi Üniversitesi BÜDOTEK Teknopark firmasıdır. MoneyShowerTech A.Ş. Ortakları Arasında İTÜ ARI TEKNOKENT, İTÜNOVA Teknoloji Transfer Ofisi, Proline ve BOĞAZİÇİ Üniversitesi Teknoloji Transfer Ofisini Bulunduran “Dezenfeksiyon” Alanında Yüksek Teknoloji Üreten, Teknolojiyi Odağına Almış Bir AR-GE ve İnovasyon Şirketidir. Alanında Uzman Mikrobiyolog ve Makine Mühendislerimizin kontrolünde KOSGEB AR-GE ve İnovasyon Desteği ile Üretim Yapılmaktadır..
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basında Biz.
        /// </summary>
        public static string BasındaBiz {
            get {
                return ResourceManager.GetString("BasındaBiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetim.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Sepetin Boş.
        /// </summary>
        public static string BasketText {
            get {
                return ResourceManager.GetString("BasketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünlerimize göz atmaya ne dersin?.
        /// </summary>
        public static string BasketText1 {
            get {
                return ResourceManager.GetString("BasketText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişe Başla.
        /// </summary>
        public static string BasketText2 {
            get {
                return ResourceManager.GetString("BasketText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayiler.
        /// </summary>
        public static string Bayilikler {
            get {
                return ResourceManager.GetString("Bayilikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Siyah.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasifik Mavisi.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Al.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sertifikalar.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renkler.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgilerimiz.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınızı yazınız....
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişime Geçin.
        /// </summary>
        public static string Contactt {
            get {
                return ResourceManager.GetString("Contactt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimle İletişime Geçin.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını Göster.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYARI : İlgili yasa gereği lütfen aşağıdaki sözleşme metnimizi 12 punto ve koyu fontta print ederek okuyunuz. Ayrıca; internet sitemize üye olan ve alış veriş yapan her müşteri, tarafımızdan düzenlenmiş olan aşağıdaki satış sözleşmemizin tüm maddelerini başka bir ihbara gerek kalmadan okumuş ve kabul etmiş sayılır!.
        /// </summary>
        public static string ContractContent11 {
            get {
                return ResourceManager.GetString("ContractContent11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyShowerTech Teknoloji AR-GE San. Ve Tic. Anonim Şirketi Mesafeli Satış Sözleşmesi.
        /// </summary>
        public static string ContractContent12 {
            get {
                return ResourceManager.GetString("ContractContent12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş bu sözleşme 13.06.2003 tarih ve 25137 sayılı Resmi Gazetede yayınlanan Mesafeli Sözleşmeler Uygulama Usul ve Esasları Hakkında Yönetmelik gereği internet üzerinden gerçekleştiren satışlar için sözleşme yapılması zorunluluğuna istinaden düzenlenmiş olup, maddeler halinde aşağıdaki gibidir..
        /// </summary>
        public static string ContractContent13 {
            get {
                return ResourceManager.GetString("ContractContent13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADDE 1 – KONU.
        /// </summary>
        public static string ContractContent14 {
            get {
                return ResourceManager.GetString("ContractContent14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş bu sözleşmenin konusu, MoneyShowerTech Teknoloji AR-GE San. Ve Tic. Anonim Şirketi’nin, ALICI’ ya satışını yaptığı, aşağıda nitelikleri ve satış fiyatı belirtilen ürünün satışı ve teslimi ile ilgili olarak 4077 sayılı Tüketicilerin Korunması Hakkındaki Kanun-Mesafeli Sözleşmeleri Uygulama Esas ve Usulleri Hakkında Yönetmelik hükümleri gereğince tarafların hak ve yükümlülüklerinin kapsamaktadır..
        /// </summary>
        public static string ContractContent15 {
            get {
                return ResourceManager.GetString("ContractContent15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADDE 2.1 – SATICI BİLGİLERİ.
        /// </summary>
        public static string ContractContent16 {
            get {
                return ResourceManager.GetString("ContractContent16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan
        ///
        ///                                            MoneyShowerTech Teknoloji AR-GE San. Ve Tic. Anonim Şirketi
        ///
        ///                                            Adres
        ///
        ///                                            Küçükyalı,Çınar Mahallesi,Yeşiltepe sokak, Rüzgar apt. NO=37 Daire=1 Maltepe/İstanbul
        ///
        ///                                            email : info@moneyshowertech.com
        ///
        ///                                            MADDE 2.2 – ALICI BİLGİLERİ
        ///
        ///                                            Müşteri ola [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent17 {
            get {
                return ResourceManager.GetString("ContractContent17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADDE 3 – SÖZLEŞME KONUSU ÜRÜN BİLGİLERİ.
        /// </summary>
        public static string ContractContent18 {
            get {
                return ResourceManager.GetString("ContractContent18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malın/ Ürünün / Hizmetin türü, miktarı, marka/modeli, rengi, adedi, satış bedeli, ödeme şekli, siparişin sonlandığı andaki bilgilerden oluşmaktadır..
        /// </summary>
        public static string ContractContent19 {
            get {
                return ResourceManager.GetString("ContractContent19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADDE 4 – GENEL HÜKÜMLER.
        /// </summary>
        public static string ContractContent20 {
            get {
                return ResourceManager.GetString("ContractContent20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.1 – ALICI, Madde 3’te belirtilen sözleşme konusu ürün veya ürünlerin temel nitelikleri, satış fiyatı ve ödeme şekli ile teslimata ilişkin tüm ön bilgileri okuyup bilgi sahibi olduğunu ve elektronik ortamda gerekli teyidi verdiğini beyan eder.
        ///
        ///                                            4.2 – Sözleşme konusu ürün veya ürünler, yasal 30 günlük süreyi aşmamak koşulu ile her bir ürün için ALICI’nın yerleşim yerinin uzaklıgına bağlı olarak ön bilgiler içinde açıklanan süre içinde ALICI veya gösterdiği adres [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent21 {
            get {
                return ResourceManager.GetString("ContractContent21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADDE 5 – CAYMA HAKKI.
        /// </summary>
        public static string ContractContent22 {
            get {
                return ResourceManager.GetString("ContractContent22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALICI, sözleşme konusu ürünün kendisine veya gösterdiği adresteki kişi/kuruluşa tesliminden itibaren (7) gün içinde cayma hakkına sahiptir. Cayma hakkının kullanılması için bu süre içinde MoneyShowerTech Teknoloji AR-GE San. Ve Tic. Anonim Şirketi’ne email veya telefon ile bildirimde bulunulması ve ürünün ilgili madde hükümleri çerçevesinde kullanılmamış olması şarttır. Bu hakkın kullanılması halinde, 3. kişiye veya ALICI’ya teslim edilen ürünün MoneyShowerTech Teknoloji AR-GE San. Ve Tic. Anonim Şirketi’ne [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent23 {
            get {
                return ResourceManager.GetString("ContractContent23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazamızda verilen tüm servisler Küçükyalı,Çınar Mahallesi,Yeşiltepe sokak, Rüzgar apt. NO=37 Daire=1 Maltepe/İstanbul adresinde kayıtlı  MoneyShowerTech Teknoloji AR-GE San. Ve Tic. Anonim Şirketi (“Şirket”) tarafından işletilir..
        /// </summary>
        public static string ContractContent2s1 {
            get {
                return ResourceManager.GetString("ContractContent2s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız, alışveriş sitelerimizden alışveriş yapan kredi kartı sahiplerinin güvenliğini ilk planda tutmaktadır. Kredi kartı bilgileriniz hiçbir şekilde sistemimizde saklanmamaktadır..
        /// </summary>
        public static string ContractContent2s10 {
            get {
                return ResourceManager.GetString("ContractContent2s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online olarak kredi kartı ile verilen siparişlerin ödeme/fatura/teslimat adresi bilgilerinin güvenilirliği firmamiz tarafından Kredi Kartları Dolandırıcılığı’na karşı denetlenmektedir. Bu yüzden, alışveriş sitelerimizden ilk defa sipariş veren müşterilerin siparişlerinin tedarik ve teslimat aşamasına gelebilmesi için öncelikle finansal ve adres/telefon bilgilerinin doğruluğunun onaylanması gereklidir. Bu bilgilerin kontrolü için gerekirse kredi kartı sahibi müşteri ile veya ilgili banka ile irtibata geçilme [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent2s11 {
            get {
                return ResourceManager.GetString("ContractContent2s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye olurken verdiğiniz tüm bilgilere sadece siz ulaşabilir ve siz değiştirebilirsiniz. Üye giriş bilgilerinizi güvenli koruduğunuz takdirde başkalarının sizinle ilgili bilgilere ulaşması ve bunları değiştirmesi mümkün değildir..
        /// </summary>
        public static string ContractContent2s12 {
            get {
                return ResourceManager.GetString("ContractContent2s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi hattı veya müşteri hizmetleri servisi bulunan ve açık adres ve telefon bilgilerinin belirtildiği İnternet alışveriş siteleri günümüzde daha fazla tercih edilmektedir. Bu sayede aklınıza takılan bütün konular hakkında detaylı bilgi alabilir, online alışveriş hizmeti sağlayan firmanın güvenirliği konusunda daha sağlıklı bilgi edinebilirsiniz..
        /// </summary>
        public static string ContractContent2s13 {
            get {
                return ResourceManager.GetString("ContractContent2s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAİL ORDER KREDİ KART BİLGİLERİ GÜVENLİĞİ.
        /// </summary>
        public static string ContractContent2s14 {
            get {
                return ResourceManager.GetString("ContractContent2s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi kartı mail-order yöntemi ile bize göndereceğiniz kimlik ve kredi kart bilgileriniz firmamız tarafından gizlilik prensibine göre saklanacaktır. Bu bilgiler olası banka ile oluşubilecek kredi kartından para çekim itirazlarına karşı 60 gün süre ile bekletilip daha sonrasında imha edilmektedir. Sipariş ettiğiniz ürünlerin bedeli karşılığında bize göndereceğiniz tarafınızdan onaylı mail-order formu bedeli dışında herhangi bir bedelin kartınızdan çekilmesi halinde doğal olarak bankaya itiraz edebilir ve bu  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent2s15 {
            get {
                return ResourceManager.GetString("ContractContent2s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜÇÜNCÜ TARAF WEB SİTELERİ VE UYGULAMALAR.
        /// </summary>
        public static string ContractContent2s16 {
            get {
                return ResourceManager.GetString("ContractContent2s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazamız,  web sitesi dâhilinde başka sitelere link verebilir. Firmamız, bu linkler vasıtasıyla erişilen sitelerin gizlilik uygulamaları ve içeriklerine yönelik herhangi bir sorumluluk taşımamaktadır. Firmamıza ait sitede yayınlanan reklamlar, reklamcılık yapan iş ortaklarımız aracılığı ile kullanıcılarımıza dağıtılır. İş bu sözleşmedeki Gizlilik Politikası Prensipleri, sadece Mağazamızın kullanımına ilişkindir, üçüncü taraf web sitelerini kapsamaz..
        /// </summary>
        public static string ContractContent2s17 {
            get {
                return ResourceManager.GetString("ContractContent2s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTİSNAİ HALLER.
        /// </summary>
        public static string ContractContent2s18 {
            get {
                return ResourceManager.GetString("ContractContent2s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıda belirtilen sınırlı hallerde Firmamız, işbu “Gizlilik Politikası” hükümleri dışında kullanıcılara ait bilgileri üçüncü kişilere açıklayabilir. Bu durumlar sınırlı sayıda olmak üzere;.
        /// </summary>
        public static string ContractContent2s19 {
            get {
                return ResourceManager.GetString("ContractContent2s19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız, çeşitli amaçlarla kişisel veriler toplayabilir. Aşağıda, toplanan kişisel verilerin nasıl ve ne şekilde toplandığı, bu verilerin nasıl ve ne şekilde korunduğu belirtilmiştir..
        /// </summary>
        public static string ContractContent2s2 {
            get {
                return ResourceManager.GetString("ContractContent2s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Kanun, Kanun Hükmünde Kararname, Yönetmelik v.b. yetkili hukuki otorite tarafından çıkarılan ve yürürlülükte olan hukuk kurallarının getirdiği zorunluluklara uymak;.
        /// </summary>
        public static string ContractContent2s20 {
            get {
                return ResourceManager.GetString("ContractContent2s20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Mağazamızın kullanıcılarla akdettiği “Üyelik Sözleşmesi”‘nin ve diğer sözleşmelerin gereklerini yerine getirmek ve bunları uygulamaya koymak amacıyla;.
        /// </summary>
        public static string ContractContent2s21 {
            get {
                return ResourceManager.GetString("ContractContent2s21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.Yetkili idari ve adli otorite tarafından usulüne göre yürütülen bir araştırma veya soruşturmanın yürütümü amacıyla kullanıcılarla ilgili bilgi talep edilmesi;.
        /// </summary>
        public static string ContractContent2s22 {
            get {
                return ResourceManager.GetString("ContractContent2s22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.Kullanıcıların hakları veya güvenliklerini korumak için bilgi vermenin gerekli olduğu hallerdir..
        /// </summary>
        public static string ContractContent2s23 {
            get {
                return ResourceManager.GetString("ContractContent2s23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-POSTA GÜVENLİĞİ.
        /// </summary>
        public static string ContractContent2s24 {
            get {
                return ResourceManager.GetString("ContractContent2s24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazamızın Müşteri Hizmetleri’ne, herhangi bir siparişinizle ilgili olarak göndereceğiniz e-postalarda, asla kredi kartı numaranızı veya şifrelerinizi yazmayınız. E-postalarda yer alan bilgiler üçüncü şahıslar tarafından görülebilir. Firmamız e-postalarınızdan aktarılan bilgilerin güvenliğini hiçbir koşulda garanti edemez..
        /// </summary>
        public static string ContractContent2s25 {
            get {
                return ResourceManager.GetString("ContractContent2s25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARAYICI ÇEREZLERİ.
        /// </summary>
        public static string ContractContent2s26 {
            get {
                return ResourceManager.GetString("ContractContent2s26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız, mağazamızı ziyaret eden kullanıcılar ve kullanıcıların web sitesini kullanımı hakkındaki bilgileri teknik bir iletişim dosyası (Çerez-Cookie) kullanarak elde edebilir. Bahsi geçen teknik iletişim dosyaları, ana bellekte saklanmak üzere bir internet sitesinin kullanıcının tarayıcısına (browser) gönderdiği küçük metin dosyalarıdır. Teknik iletişim dosyası site hakkında durum ve tercihleri saklayarak İnternet’in kullanımını kolaylaştırır..
        /// </summary>
        public static string ContractContent2s27 {
            get {
                return ResourceManager.GetString("ContractContent2s27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik iletişim dosyası,  siteyi kaç kişinin ziyaret ettiğini, bir kişinin siteyi hangi amaçla, kaç kez ziyaret ettiğini ve ne kadar sitede kaldıkları hakkında istatistiksel bilgileri elde etmeye ve kullanıcılar için özel tasarlanmış kullanıcı sayfalarından  dinamik olarak reklam ve içerik üretilmesine yardımcı olur. Teknik iletişim dosyası, ana bellekte veya e-postanızdan veri veya başkaca herhangi bir kişisel bilgi almak için tasarlanmamıştır. Tarayıcıların pek çoğu başta teknik iletişim dosyasını kabul e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent2s28 {
            get {
                return ResourceManager.GetString("ContractContent2s28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız, işbu “Gizlilik Politikası” hükümlerini dilediği zaman sitede yayınlamak veya kullanıcılara elektronik posta göndermek veya sitesinde yayınlamak suretiyle değiştirebilir. Gizlilik Politikası hükümleri değiştiği takdirde, yayınlandığı tarihte yürürlük kazanır..
        /// </summary>
        public static string ContractContent2s29 {
            get {
                return ResourceManager.GetString("ContractContent2s29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik veya Mağazamız üzerindeki çeşitli form ve anketlerin doldurulması suretiyle üyelerin kendileriyle ilgili bir takım kişisel bilgileri (isim-soy isim, firma bilgileri, telefon, adres veya e-posta adresleri gibi) Mağazamız tarafından faturalandırma amacı ile toplanmaktadır..
        /// </summary>
        public static string ContractContent2s3 {
            get {
                return ResourceManager.GetString("ContractContent2s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik politikamız ile ilgili her türlü soru ve önerileriniz için info@moneyshowertech.com  adresine email gönderebilirsiniz. Firmamız’a ait aşağıdaki iletişim bilgilerinden ulaşabilirsiniz..
        /// </summary>
        public static string ContractContent2s30 {
            get {
                return ResourceManager.GetString("ContractContent2s30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Ünvanı: MoneyShowerTech Teknoloji AR-GE San. Ve Tic. Anonim Şirketi.
        /// </summary>
        public static string ContractContent2s31 {
            get {
                return ResourceManager.GetString("ContractContent2s31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız bazı dönemlerde müşterilerine ve üyelerine kampanya bilgileri, yeni ürünler hakkında bilgiler, promosyon teklifleri gönderebilir. Üyelerimiz bu gibi bilgileri alıp almama konusunda her türlü seçimi üye olurken yapabilir, sonrasında üye girişi yaptıktan sonra hesap bilgileri bölümünden bu seçimi değiştirilebilir ya da kendisine gelen bilgilendirme iletisindeki linkle bildirim yapabilir..
        /// </summary>
        public static string ContractContent2s4 {
            get {
                return ResourceManager.GetString("ContractContent2s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazamız üzerinden veya eposta ile gerçekleştirilen onay sürecinde, üyelerimiz tarafından mağazamıza elektronik ortamdan iletilen kişisel bilgiler, Üyelerimiz ile yaptığımız “Kullanıcı Sözleşmesi” ile belirlenen amaçlar ve kapsam dışında üçüncü kişilere açıklanmayacaktır..
        /// </summary>
        public static string ContractContent2s5 {
            get {
                return ResourceManager.GetString("ContractContent2s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemle ilgili sorunların tanımlanması ve verilen hizmet ile ilgili çıkabilecek sorunların veya uyuşmazlıkların hızla çözülmesi için, Firmamız, üyelerinin IP adresini kaydetmekte ve bunu kullanmaktadır. IP adresleri, kullanıcıları genel bir şekilde tanımlamak ve kapsamlı demografik bilgi toplamak amacıyla da kullanılabilir..
        /// </summary>
        public static string ContractContent2s6 {
            get {
                return ResourceManager.GetString("ContractContent2s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız, Üyelik Sözleşmesi ile belirlenen amaçlar ve kapsam dışında da, talep edilen bilgileri kendisi veya işbirliği içinde olduğu kişiler tarafından doğrudan pazarlama yapmak amacıyla kullanabilir.  Kişisel bilgiler, gerektiğinde kullanıcıyla temas kurmak için de kullanılabilir. Firmamız tarafından talep edilen bilgiler veya kullanıcı tarafından sağlanan bilgiler veya Mağazamız üzerinden yapılan işlemlerle ilgili bilgiler; Firmamız ve işbirliği içinde olduğu kişiler tarafından, “Üyelik Sözleşmesi” ile be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent2s7 {
            get {
                return ResourceManager.GetString("ContractContent2s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız, gizli bilgileri kesinlikle özel ve gizli tutmayı, bunu bir sır saklama yükümü olarak addetmeyi ve gizliliğin sağlanması ve sürdürülmesi, gizli bilginin tamamının veya herhangi bir kısmının kamu alanına girmesini veya yetkisiz kullanımını veya üçüncü bir kişiye ifşasını önlemek için gerekli tüm tedbirleri almayı ve gerekli özeni göstermeyi taahhüt etmektedir..
        /// </summary>
        public static string ContractContent2s8 {
            get {
                return ResourceManager.GetString("ContractContent2s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KREDİ KARTI GÜVENLİĞİ.
        /// </summary>
        public static string ContractContent2s9 {
            get {
                return ResourceManager.GetString("ContractContent2s9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site içi kullanım şartları.
        /// </summary>
        public static string ContractContent3s1 {
            get {
                return ResourceManager.GetString("ContractContent3s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fikri Mülkiyet Hakları.
        /// </summary>
        public static string ContractContent3s10 {
            get {
                return ResourceManager.GetString("ContractContent3s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1. İşbu Site’de yer alan ünvan, işletme adı, marka, patent, logo, tasarım, bilgi ve yöntem gibi tescilli veya tescilsiz tüm fikri mülkiyet hakları site işleteni ve sahibi firmaya veya belirtilen ilgilisine ait olup, ulusal ve uluslararası hukukun koruması altındadır. İşbu Site’nin ziyaret edilmesi veya bu Site’deki hizmetlerden yararlanılması söz konusu fikri mülkiyet hakları konusunda hiçbir hak vermez..
        /// </summary>
        public static string ContractContent3s11 {
            get {
                return ResourceManager.GetString("ContractContent3s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2. Site’de yer alan bilgiler hiçbir şekilde çoğaltılamaz, yayınlanamaz, kopyalanamaz, sunulamaz ve/veya aktarılamaz. Site’nin bütünü veya bir kısmı diğer bir internet sitesinde izinsiz olarak kullanılamaz..
        /// </summary>
        public static string ContractContent3s12 {
            get {
                return ResourceManager.GetString("ContractContent3s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizli Bilgi
        ///                                            3.1. Firma, site üzerinden kullanıcıların ilettiği kişisel bilgileri 3. Kişilere açıklamayacaktır. Bu kişisel bilgiler; kişi adı-soyadı, adresi, telefon numarası, cep telefonu, e-posta adresi gibi Kullanıcı’yı tanımlamaya yönelik her türlü diğer bilgiyi içermekte olup, kısaca ‘Gizli Bilgiler’ olarak anılacaktır..
        /// </summary>
        public static string ContractContent3s13 {
            get {
                return ResourceManager.GetString("ContractContent3s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2. Kullanıcı, sadece tanıtım, reklam, kampanya, promosyon, duyuru vb. pazarlama faaliyetleri kapsamında kullanılması ile sınırlı olmak üzere, Site’nin sahibi olan firmanın kendisine ait iletişim, portföy durumu ve demografik bilgilerini iştirakleri ya da bağlı bulunduğu grup şirketleri ile paylaşmasına muvafakat ettiğini kabul ve beyan eder. Bu kişisel bilgiler firma bünyesinde müşteri profili belirlemek, müşteri profiline uygun promosyon ve kampanyalar sunmak ve istatistiksel çalışmalar yapmak amacıyla k [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent3s14 {
            get {
                return ResourceManager.GetString("ContractContent3s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3. Gizli Bilgiler, ancak resmi makamlarca usulü dairesinde bu bilgilerin talep edilmesi halinde ve yürürlükteki emredici mevzuat hükümleri gereğince resmi makamlara açıklama yapılmasının zorunlu olduğu durumlarda resmi makamlara açıklanabilecektir..
        /// </summary>
        public static string ContractContent3s15 {
            get {
                return ResourceManager.GetString("ContractContent3s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garanti Vermeme:.
        /// </summary>
        public static string ContractContent3s16 {
            get {
                return ResourceManager.GetString("ContractContent3s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞBU SÖZLEŞME MADDESİ UYGULANABİLİR KANUNUN İZİN VERDİĞİ AZAMİ ÖLÇÜDE GEÇERLİ OLACAKTIR.  FİRMA TARAFINDAN SUNULAN HİZMETLER “OLDUĞU GİBİ” VE “MÜMKÜN OLDUĞU” TEMELDE SUNULMAKTA VE PAZARLANABİLİRLİK, BELİRLİ BİR AMACA UYGUNLUK VEYA İHLAL ETMEME KONUSUNDA TÜM ZIMNİ GARANTİLER DE DÂHİL OLMAK ÜZERE HİZMETLER VEYA UYGULAMA İLE İLGİLİ OLARAK (BUNLARDA YER ALAN TÜM BİLGİLER DÂHİL) SARİH VEYA ZIMNİ, KANUNİ VEYA BAŞKA BİR NİTELİKTE HİÇBİR GARANTİDE BULUNMAMAKTADIR..
        /// </summary>
        public static string ContractContent3s17 {
            get {
                return ResourceManager.GetString("ContractContent3s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt ve Güvenlik
        ///                                            Kullanıcı, doğru, eksiksiz ve güncel kayıt bilgilerini vermek zorundadır. Aksi halde bu Sözleşme ihlal edilmiş sayılacak ve Kullanıcı bilgilendirilmeksizin hesap kapatılabilecektir..
        /// </summary>
        public static string ContractContent3s18 {
            get {
                return ResourceManager.GetString("ContractContent3s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı, site ve üçüncü taraf sitelerdeki şifre ve hesap güvenliğinden kendisi sorumludur. Aksi halde oluşacak veri kayıplarından ve güvenlik ihlallerinden veya donanım ve cihazların zarar görmesinden Firma sorumlu tutulamaz..
        /// </summary>
        public static string ContractContent3s19 {
            get {
                return ResourceManager.GetString("ContractContent3s19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen sitemizi kullanmadan evvel bu ‘site kullanım şartları’nı dikkatlice okuyunuz..
        /// </summary>
        public static string ContractContent3s2 {
            get {
                return ResourceManager.GetString("ContractContent3s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mücbir Sebep.
        /// </summary>
        public static string ContractContent3s20 {
            get {
                return ResourceManager.GetString("ContractContent3s20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarafların kontrolünde olmayan; tabii afetler, yangın, patlamalar, iç savaşlar, savaşlar, ayaklanmalar, halk hareketleri, seferberlik ilanı, grev, lokavt ve salgın hastalıklar, altyapı ve internet arızaları, elektrik kesintisi gibi sebeplerden (aşağıda birlikte “Mücbir Sebep” olarak anılacaktır.) dolayı sözleşmeden doğan yükümlülükler taraflarca ifa edilemez hale gelirse, taraflar bundan sorumlu değildir. Bu sürede Taraflar’ın işbu Sözleşme’den doğan hak ve yükümlülükleri askıya alınır..
        /// </summary>
        public static string ContractContent3s21 {
            get {
                return ResourceManager.GetString("ContractContent3s21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sözleşmenin Bütünlüğü ve Uygulanabilirlik.
        /// </summary>
        public static string ContractContent3s22 {
            get {
                return ResourceManager.GetString("ContractContent3s22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşbu sözleşme şartlarından biri, kısmen veya tamamen geçersiz hale gelirse, sözleşmenin geri kalanı geçerliliğini korumaya devam eder..
        /// </summary>
        public static string ContractContent3s23 {
            get {
                return ResourceManager.GetString("ContractContent3s23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sözleşmede Yapılacak Değişiklikler.
        /// </summary>
        public static string ContractContent3s24 {
            get {
                return ResourceManager.GetString("ContractContent3s24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma, dilediği zaman sitede sunulan hizmetleri ve işbu sözleşme şartlarını kısmen veya tamamen değiştirebilir. Değişiklikler sitede yayınlandığı tarihten itibaren geçerli olacaktır. Değişiklikleri takip etmek Kullanıcı’nın sorumluluğundadır. Kullanıcı, sunulan hizmetlerden yararlanmaya devam etmekle bu değişiklikleri de kabul etmiş sayılır..
        /// </summary>
        public static string ContractContent3s25 {
            get {
                return ResourceManager.GetString("ContractContent3s25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tebligat.
        /// </summary>
        public static string ContractContent3s26 {
            get {
                return ResourceManager.GetString("ContractContent3s26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşbu Sözleşme ile ilgili taraflara gönderilecek olan tüm bildirimler, Firma’nın bilinen e.posta adresi ve kullanıcının üyelik formunda belirttiği e.posta adresi vasıtasıyla yapılacaktır. Kullanıcı, üye olurken belirttiği adresin geçerli tebligat adresi olduğunu, değişmesi durumunda 5 gün içinde yazılı olarak diğer tarafa bildireceğini, aksi halde bu adrese yapılacak tebligatların geçerli sayılacağını kabul eder..
        /// </summary>
        public static string ContractContent3s27 {
            get {
                return ResourceManager.GetString("ContractContent3s27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delil Sözleşmesi.
        /// </summary>
        public static string ContractContent3s28 {
            get {
                return ResourceManager.GetString("ContractContent3s28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taraflar arasında işbu sözleşme ile ilgili işlemler için çıkabilecek her türlü uyuşmazlıklarda Taraflar’ın defter, kayıt ve belgeleri ile ve bilgisayar kayıtları ve faks kayıtları 6100 sayılı Hukuk Muhakemeleri Kanunu uyarınca delil olarak kabul edilecek olup, kullanıcı bu kayıtlara itiraz etmeyeceğini kabul eder..
        /// </summary>
        public static string ContractContent3s29 {
            get {
                return ResourceManager.GetString("ContractContent3s29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alışveriş sitesini kullanan ve alışveriş yapan müşterilerimiz aşağıdaki şartları kabul etmiş varsayılmaktadır:.
        /// </summary>
        public static string ContractContent3s3 {
            get {
                return ResourceManager.GetString("ContractContent3s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyuşmazlıkların Çözümü.
        /// </summary>
        public static string ContractContent3s30 {
            get {
                return ResourceManager.GetString("ContractContent3s30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşbu Sözleşme’nin uygulanmasından veya yorumlanmasından doğacak her türlü uyuşmazlığın çözümünde İstanbul (Merkez) Adliyesi Mahkemeleri ve İcra Daireleri yetkilidir..
        /// </summary>
        public static string ContractContent3s31 {
            get {
                return ResourceManager.GetString("ContractContent3s31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemizdeki web sayfaları ve ona bağlı tüm sayfalar (‘site’) Küçükyalı,Çınar Mahallesi,Yeşiltepe sokak, Rüzgar apt. NO=37 Daire=1 Maltepe/İstanbul adresindeki MoneyShowerTech Teknoloji AR-GE San. Ve Tic. Anonim Şirketi firmasının (Firma) malıdır ve onun tarafından işletilir. Sizler (‘Kullanıcı’) sitede sunulan tüm hizmetleri kullanırken aşağıdaki şartlara tabi olduğunuzu, sitedeki hizmetten yararlanmakla ve kullanmaya devam etmekle; Bağlı olduğunuz yasalara göre sözleşme imzalama hakkına, yetkisine ve hukuk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent3s4 {
            get {
                return ResourceManager.GetString("ContractContent3s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşbu sözleşme taraflara sözleşme konusu site ile ilgili hak ve yükümlülükler yükler ve taraflar işbu sözleşmeyi kabul ettiklerinde bahsi geçen hak ve yükümlülükleri eksiksiz, doğru, zamanında, işbu sözleşmede talep edilen şartlar dâhilinde yerine getireceklerini beyan ederler..
        /// </summary>
        public static string ContractContent3s5 {
            get {
                return ResourceManager.GetString("ContractContent3s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORUMLULUKLAR.
        /// </summary>
        public static string ContractContent3s6 {
            get {
                return ResourceManager.GetString("ContractContent3s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.Firma, fiyatlar ve sunulan ürün ve hizmetler üzerinde değişiklik yapma hakkını her zaman saklı tutar.
        ///
        ///                                            b.Firma, üyenin sözleşme konusu hizmetlerden, teknik arızalar dışında yararlandırılacağını kabul ve taahhüt eder.
        ///
        ///                                            c.Kullanıcı, sitenin kullanımında tersine mühendislik yapmayacağını ya da bunların kaynak kodunu bulmak veya elde etmek amacına yönelik herhangi bir başka işlemde bulunmayacağını aksi halde ve 3. Kişi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent3s7 {
            get {
                return ResourceManager.GetString("ContractContent3s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.Kullanıcı, site içindeki faaliyetlerinde, sitenin herhangi bir bölümünde veya iletişimlerinde genel ahlaka ve adaba aykırı, kanuna aykırı, 3. Kişilerin haklarını zedeleyen, yanıltıcı, saldırgan, müstehcen, pornografik, kişilik haklarını zedeleyen, telif haklarına aykırı, yasa dışı faaliyetleri teşvik eden içerikler üretmeyeceğini, paylaşmayacağını kabul eder. Aksi halde oluşacak zarardan tamamen kendisi sorumludur ve bu durumda ‘Site’ yetkilileri, bu tür hesapları askıya alabilir, sona erdirebilir, yasal  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContractContent3s8 {
            get {
                return ResourceManager.GetString("ContractContent3s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.Sitenin üyelerinin birbirleri veya üçüncü şahıslarla olan ilişkileri kendi sorumluluğundadır..
        /// </summary>
        public static string ContractContent3s9 {
            get {
                return ResourceManager.GetString("ContractContent3s9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesafeli Satış Sözleşmesi.
        /// </summary>
        public static string ContractTitle1 {
            get {
                return ResourceManager.GetString("ContractTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik ve Güvenlik Politikası.
        /// </summary>
        public static string ContractTitle2 {
            get {
                return ResourceManager.GetString("ContractTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Sözleşmesi.
        /// </summary>
        public static string ContractTitle3 {
            get {
                return ResourceManager.GetString("ContractTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşterilerimiz.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayi Olmak İçin Bayilik Formu.
        /// </summary>
        public static string DealerButonText {
            get {
                return ResourceManager.GetString("DealerButonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Kodu.
        /// </summary>
        public static string DiscountCode {
            get {
                return ResourceManager.GetString("DiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribütör olmak için Distribütör formu.
        /// </summary>
        public static string DistButonText {
            get {
                return ResourceManager.GetString("DistButonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribütörler.
        /// </summary>
        public static string Distribütörler {
            get {
                return ResourceManager.GetString("Distribütörler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string Fiyat {
            get {
                return ResourceManager.GetString("Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizi Takip Edin.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzay Grisi.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string İletişim {
            get {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanmadan önce kullanma talimatını okuyunuz..
        /// </summary>
        public static string InstructionsContent1 {
            get {
                return ResourceManager.GetString("InstructionsContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünün cansız yüzeylerin dezenfeksiyonunda kullanımı tamamen güvenlidir..
        /// </summary>
        public static string InstructionsContent10 {
            get {
                return ResourceManager.GetString("InstructionsContent10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çocukların erişemeyeceği yerlerde saklayınız..
        /// </summary>
        public static string InstructionsContent2 {
            get {
                return ResourceManager.GetString("InstructionsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göze ve cilde doğrudan temasından kaçınılacak şekilde dikkatli kullanılmalıdır..
        /// </summary>
        public static string InstructionsContent3 {
            get {
                return ResourceManager.GetString("InstructionsContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün çocuk emniyetli niteliktedir..
        /// </summary>
        public static string InstructionsContent4 {
            get {
                return ResourceManager.GetString("InstructionsContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün FDA onaylı Ultraviyole C tipi ışık teknolojisi içerir..
        /// </summary>
        public static string InstructionsContent5 {
            get {
                return ResourceManager.GetString("InstructionsContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güçlendirilmiş Ultraviyole Işık teknolojisi ile temassız ve saniyeler içerisinde anlık dezenfeksiyon sağlar..
        /// </summary>
        public static string InstructionsContent6 {
            get {
                return ResourceManager.GetString("InstructionsContent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultraviyole ışın teknolojisi radyoaktif olmayan bir teknolojidir..
        /// </summary>
        public static string InstructionsContent7 {
            get {
                return ResourceManager.GetString("InstructionsContent7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Işının temas ettiği nesneler radyoaktif hale gelmez..
        /// </summary>
        public static string InstructionsContent8 {
            get {
                return ResourceManager.GetString("InstructionsContent8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünün içerdiği elektronik dezenfeksiyon teknolojisi, kimyasal dezenfektanların aksine herhangi bir kalıntı bırakmaz. Kimyasal dezenfektan kullanmadan temizlik yapma imkanı sağlar..
        /// </summary>
        public static string InstructionsContent9 {
            get {
                return ResourceManager.GetString("InstructionsContent9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Talimatları.
        /// </summary>
        public static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talimatlar.
        /// </summary>
        public static string InstructionsTitle2 {
            get {
                return ResourceManager.GetString("InstructionsTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkler.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrobiyolojik Analizler ve Raporlar.
        /// </summary>
        public static string MikrobiyolojikAnaliz {
            get {
                return ResourceManager.GetString("MikrobiyolojikAnaliz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Counting Shower, Para sayma makinelerine hasarsız entegre olmakta ve bankalara şubelerindeki müşterilerine temiz para sunma imkanı sağlamaktadır..
        /// </summary>
        public static string MoneyCountingContent {
            get {
                return ResourceManager.GetString("MoneyCountingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neden Money Counting Shower?.
        /// </summary>
        public static string MoneyCountingShowerContent1 {
            get {
                return ResourceManager.GetString("MoneyCountingShowerContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 899.90₺.
        /// </summary>
        public static string MoneyCountingShowerNPrice {
            get {
                return ResourceManager.GetString("MoneyCountingShowerNPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 499.90₺.
        /// </summary>
        public static string MoneyCountingShowerNPrice2 {
            get {
                return ResourceManager.GetString("MoneyCountingShowerNPrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 299.90₺.
        /// </summary>
        public static string MoneyCountingShowerNPrice3 {
            get {
                return ResourceManager.GetString("MoneyCountingShowerNPrice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 999.99₺.
        /// </summary>
        public static string MoneyCountingShowerOPrice {
            get {
                return ResourceManager.GetString("MoneyCountingShowerOPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Shower teknolojisi kağıt paraları, ATM içerisine entegre edilebilen, temassız ve anlık dezenfeksiyon sağlayan bir sistem ile temizlemektedir..
        /// </summary>
        public static string MoneyShowerContent {
            get {
                return ResourceManager.GetString("MoneyShowerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neden MoneyShower?.
        /// </summary>
        public static string MoneyShowerContent1 {
            get {
                return ResourceManager.GetString("MoneyShowerContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayiler.
        /// </summary>
        public static string OurDealerships {
            get {
                return ResourceManager.GetString("OurDealerships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribütörler.
        /// </summary>
        public static string OurDistributors {
            get {
                return ResourceManager.GetString("OurDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnerlerimiz.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Sayfasına Git.
        /// </summary>
        public static string PaymentText {
            get {
                return ResourceManager.GetString("PaymentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kum Pembesi.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunum.
        /// </summary>
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürününüz.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Detayı.
        /// </summary>
        public static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayimiz Veya Distribütör Olmak İçin Bizimle İletişime Geçin.
        /// </summary>
        public static string SiteContent {
            get {
                return ResourceManager.GetString("SiteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O kadar hızlı !.
        /// </summary>
        public static string SliderContent {
            get {
                return ResourceManager.GetString("SliderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sağlığınız Bizim İçin Değerlidir..
        /// </summary>
        public static string SliderText {
            get {
                return ResourceManager.GetString("SliderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS.
        /// </summary>
        public static string SSS {
            get {
                return ResourceManager.GetString("SSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower ile cansız tüm yüzeyleri %99’a varan oranlarda anlık dezenfekte edebilirsiniz. Örneğin özellikle hijyenik durumundan endişe duyulan umumi tuvaletler, kapı kolları, asansör düğmeleri, restoranlardaki çatal, bıçak ve bardaklar, telefonlar, biberon ve emzikler, kozmetik eşyalar, bilgisayar fareleri, bilgisayar klavyeleri, teneke kutu içeceklerin dış yüzeyleri, otobüs tutacakları, lamba düğmeleri, madeni ve kağıt paralar, ATM düğmeleri ve dokunmatik ekranları, kırmızı ışık butonları, yiyecek – içec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SSSContent1 {
            get {
                return ResourceManager.GetString("SSSContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower elektronik dezenfektanınız teslimat tarihinden itibaren 2 yıl süre ile garanti kapsamındadır..
        /// </summary>
        public static string SSSContent10 {
            get {
                return ResourceManager.GetString("SSSContent10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower temas ettiğiniz ya da edeceğiniz yüzeylerin mikroorganizmalardan arındırılması amacı ile geliştirilmiştir. Dolayısıyla ürünün canlılar üzerinde kullanımı tavsiye edilmemektedir.
        ///
        ///                    Thing Shower’ınızı elleriniz de dahil olmak üzere vücudunuzun herhangi bir bölgesinin dezenfeksiyonu için kullanmayınız. Ayrıca Thing Shower’ınızı evcil hayvanlarınız ve bitkilerinizin temizliğinde de kullanmanız tavsiye edilmemektedir..
        /// </summary>
        public static string SSSContent2 {
            get {
                return ResourceManager.GetString("SSSContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower ile dezenfekte ettiğiniz eşyalarınızı mikrobiyal olarak kontamine olmadığı sürece güvenli bir şekilde kullanabilirsiniz. Ancak havada bile mikroorganizmaların bulunduğunu ve dezenfekte ettiğiniz ürünü açık ortamda bıraktığınız sürece kontamine olacağını hatırlatmak isteriz. Bu nedenle eşyalarınızı kullanmadan hemen önce Thing Shower ile dezenfekte etmeniz tavsiye edilmektedir..
        /// </summary>
        public static string SSSContent3 {
            get {
                return ResourceManager.GetString("SSSContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower dezenfekte edilecek yüzeye 1 cm mesafeden tutulduğunda 28 cm2’lik bir alanı 1 saniyede bakteri, virüs ve parazitler de tüm mikroorganizmalardan %99,9’a varan oranda arındırmaktadır. Örneğin ortalama olarak telefonlar 1 saniyede, kulaklıklar 1 saniyede, biberon emzikleri ve emzikler 2 saniyede, çatal kaşık ve bıçaklar 1 saniyede, bardaklar 2 saniyede, asansör düğmeleri 1 saniyede, lamba düğmeleri 1 saniyede, madeni paraların bir yüzeyi 1 saniyede, kağıt paraların bir yüzeyi 1 saniyede, kapı koll [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SSSContent4 {
            get {
                return ResourceManager.GetString("SSSContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower elektronik dezenfektanınızı dezenfekte edeceğiniz yüzeye maksimum 1 cm uzaklıktan yüzeye dik bir şekilde tutmanız tavsiye edilmektedir. Thing Shower dezenfekte edilecek yüzeye 1 cm (1 parmak kalınlığı) mesafeden tutulduğunda 9 cm2’lik bir alanı (1 TL madeni parası kadar alanı) 1 saniyede bakteri, virüs ve parazitler de tüm mikroorganizmalardan %99’a varan oranda arındırmaktadır..
        /// </summary>
        public static string SSSContent5 {
            get {
                return ResourceManager.GetString("SSSContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower kullanım talimatına uygun bir şekilde kullanıldığında insan, hayvan ve çevreye herhangi bir zarar vermemektedir ve kullanımı tamamen güvenlidir..
        /// </summary>
        public static string SSSContent6 {
            get {
                return ResourceManager.GetString("SSSContent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır. Thing Shower temas ettiğiniz ya da edeceğiniz cansız yüzeylerin mikroorganizmalardan arındırılması amacı ile geliştirilmiştir. Dolayısıyla ürünün canlılar üzerinde kullanımı tavsiye edilmemektedir.
        ///
        ///                    Thing Shower’ınızı elleriniz de dahil olmak üzere vücudunuzun herhangi bir bölgesinin dezenfeksiyonu için kullanmayınız.
        /// </summary>
        public static string SSSContent7 {
            get {
                return ResourceManager.GetString("SSSContent7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower elektronik dezenfektanınızın kullanım ömrü pil hariç 5 yıldır ve teslimat tarihinden itibaren 2 yıl süre ile garanti kapsamındadır.
        ///
        ///                    Thing Shower’ınızda şarj edilebilir pil kullanılmaktadır. Şarj edilebilir piller kısıtlı kullanım ömrüne sahiptirler..
        /// </summary>
        public static string SSSContent8 {
            get {
                return ResourceManager.GetString("SSSContent8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower herhangi bir arıza olmadığı sürece tam verimle çalışacak şekilde tasarlanmıştır. Bu nedenle arızalanmadığı sürece Thing Shower’ınız saniyeler içerisinde %99’a varan oranlarda temassız ve anlık dezenfeksiyon yapmaya devam edecektir..
        /// </summary>
        public static string SSSContent9 {
            get {
                return ResourceManager.GetString("SSSContent9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıkça Sorulan Sorular.
        /// </summary>
        public static string SSSTitle {
            get {
                return ResourceManager.GetString("SSSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower ile neleri dezenfekte edebilirim ?.
        /// </summary>
        public static string SSSTitle1 {
            get {
                return ResourceManager.GetString("SSSTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazın garanti süresi ne kadar?.
        /// </summary>
        public static string SSSTitle10 {
            get {
                return ResourceManager.GetString("SSSTitle10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower ile neleri dezenfekte etmemeliyim ?.
        /// </summary>
        public static string SSSTitle2 {
            get {
                return ResourceManager.GetString("SSSTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezenfekte ettiğimizde ne kadar süre ile işlemi tekrarlıyoruz ?.
        /// </summary>
        public static string SSSTitle3 {
            get {
                return ResourceManager.GetString("SSSTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower cihazı uygulama yapılan yüzeydeki patojenleri kaç saniyede yok ediyor ?.
        /// </summary>
        public static string SSSTitle4 {
            get {
                return ResourceManager.GetString("SSSTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazı yüzeye ne kadar uzaklıktan tutmam gerekiyor ?.
        /// </summary>
        public static string SSSTitle5 {
            get {
                return ResourceManager.GetString("SSSTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan sağlığına bilinen bir zararı var mı ?.
        /// </summary>
        public static string SSSTitle6 {
            get {
                return ResourceManager.GetString("SSSTitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellerimi Thing Shower ile temizleyebilir miyim ?.
        /// </summary>
        public static string SSSTitle7 {
            get {
                return ResourceManager.GetString("SSSTitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazın kullanım ömrü var mı ?.
        /// </summary>
        public static string SSSTitle8 {
            get {
                return ResourceManager.GetString("SSSTitle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazı bir süre kullandıktan sonra verimi düşüyor mu ?.
        /// </summary>
        public static string SSSTitle9 {
            get {
                return ResourceManager.GetString("SSSTitle9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürününüz Sepete Başarıyla Eklendi..
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string SuccessOk {
            get {
                return ResourceManager.GetString("SuccessOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog.
        /// </summary>
        public static string ThingShowerCatalog {
            get {
                return ResourceManager.GetString("ThingShowerCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neden ThingShower E-Dezenfektan ?.
        /// </summary>
        public static string ThingShowerContent1 {
            get {
                return ResourceManager.GetString("ThingShowerContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmişten günümüze yüzeylerde bulunan patojenlerin yok edilmesi amacı ile çeşitli yöntemler uygulanmaktadır. Bunlardan en çok tercih edileni kimyasal dezenfektanlar ve Ultraviyole Işık teknolojisidir. Kimyasal dezenfektanların büyük bir kısmı kimyasal atık bırakmaktadır ve insan sağlığı için uzun süreli maruz kalımlarda toksik etki göstermektedir. Ultraviyole Işık teknolojisi, kimyasal atık bırakmaması, uygun fiyatlı olması, radyoaktif olmaması, FDA onaylı olması ve uzun süreli uygulamalarda 4 logaritmik az [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ThingShowerContent10 {
            get {
                return ResourceManager.GetString("ThingShowerContent10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garanti.
        /// </summary>
        public static string ThingShowerContent11 {
            get {
                return ResourceManager.GetString("ThingShowerContent11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Yıl Koşulsuz Garanti..
        /// </summary>
        public static string ThingShowerContent12 {
            get {
                return ResourceManager.GetString("ThingShowerContent12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patentli Teknoloji.
        /// </summary>
        public static string ThingShowerContent13 {
            get {
                return ResourceManager.GetString("ThingShowerContent13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %99.99 Yüzey temizleme teknolojisi..
        /// </summary>
        public static string ThingShowerContent14 {
            get {
                return ResourceManager.GetString("ThingShowerContent14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR-GE.
        /// </summary>
        public static string ThingShowerContent15 {
            get {
                return ResourceManager.GetString("ThingShowerContent15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İTÜ ARI TEKNOKENT’te geliştirildi..
        /// </summary>
        public static string ThingShowerContent16 {
            get {
                return ResourceManager.GetString("ThingShowerContent16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ile güvenli alışveriş !.
        /// </summary>
        public static string ThingShowerContent17 {
            get {
                return ResourceManager.GetString("ThingShowerContent17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişler takip eden ilk iş günü içinde kargoya verilir..
        /// </summary>
        public static string ThingShowerContent18 {
            get {
                return ResourceManager.GetString("ThingShowerContent18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ücretsiz Kargo(MNG KARGO).
        /// </summary>
        public static string ThingShowerContent19 {
            get {
                return ResourceManager.GetString("ThingShowerContent19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İTÜ Arı Teknokent ve Boğaziçi Üniversitesi BÜDOTEK Teknopark  firması ürünüdür. Uzman mikrobiyologlar ile birlikte geliştirilmiştir..
        /// </summary>
        public static string ThingShowerContent2 {
            get {
                return ResourceManager.GetString("ThingShowerContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit Seçenekleri.
        /// </summary>
        public static string ThingShowerContent3 {
            get {
                return ResourceManager.GetString("ThingShowerContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankalar.
        /// </summary>
        public static string ThingShowerContent4 {
            get {
                return ResourceManager.GetString("ThingShowerContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit Sayısı.
        /// </summary>
        public static string ThingShowerContent5 {
            get {
                return ResourceManager.GetString("ThingShowerContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Ödeme.
        /// </summary>
        public static string ThingShowerContent6 {
            get {
                return ResourceManager.GetString("ThingShowerContent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string ThingShowerContent7 {
            get {
                return ResourceManager.GetString("ThingShowerContent7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaşamın her yerinde binlerce çeşitten oluşan milyarlarca bakteri, virüs, parazit gibi mikroorganizmalar bulunmaktadır. Bunlardan bir kısmı insan sağlığına faydalı, bir kısmı zararsız ve bazıları ise zararlı mikroorganizmalardır. Zararlı mikroorganizmalara patojen denir ve belli bir miktarda vücuda alındığında çeşitli hastalıklara sebep olmaktadırlar. Patojenlerden bazılarının 1 adeti bile çok ciddi semptomlara sebep olurken bazılarının hastalık yapıcı doz miktarı binlerce adeti bulabilmektedir..
        /// </summary>
        public static string ThingShowerContent8 {
            get {
                return ResourceManager.GetString("ThingShowerContent8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az pişirilmiş gıdalar, hijyen kurallarına uyulmadan hazırlanmış gıdalar, kağıt paralar, tuvalet, kapı kolları, toplu taşıma araçları, restoranlardaki yemek takımları gibi toplumlar tarafından ortak kullanılmakta olan eşyalar bu hastalık yapıcı patojen mikroorganizmaların çok sık rastlandığı ortamlar olarak bilinmektedir. Bahsi geçen gıdalar vücuda alındığında, bahsi geçen eşyalara temas edildiğinde insan sağlığı için zararlı etkiler görülmektedir. Bu nedenle gıdaların hijyen kurallarına uygun olarak iyi piş [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ThingShowerContent9 {
            get {
                return ResourceManager.GetString("ThingShowerContent9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geleneksel ultraviyole ışık teknolojisinden binlerce kat güçlendirilmiş patentli bir Işık teknolojisi üreterek milisaniyeler içerisinde %99,99’a varan dezenfeksiyon sağlayan temassız, elektronik ve portatif dezenfektandır..
        /// </summary>
        public static string ThingShowerIndex {
            get {
                return ResourceManager.GetString("ThingShowerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://iyzi.link/AFk4Tg.
        /// </summary>
        public static string ThingShowerLink {
            get {
                return ResourceManager.GetString("ThingShowerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 499.90₺.
        /// </summary>
        public static string ThingShowerNPrice {
            get {
                return ResourceManager.GetString("ThingShowerNPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 324.99₺.
        /// </summary>
        public static string ThingShowerNPrice2 {
            get {
                return ResourceManager.GetString("ThingShowerNPrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 216.99₺.
        /// </summary>
        public static string ThingShowerNPrice3 {
            get {
                return ResourceManager.GetString("ThingShowerNPrice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 799.99₺.
        /// </summary>
        public static string ThingShowerOPrice {
            get {
                return ResourceManager.GetString("ThingShowerOPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Shower, Işık teknolojisi üreterek milisaniyeler içerisinde %99,99’a varan dezenfeksiyon sağlayan temassız, elektronik ve portatif dezenfektandır..
        /// </summary>
        public static string ThingShowerShortContent {
            get {
                return ResourceManager.GetString("ThingShowerShortContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünlerimiz.
        /// </summary>
        public static string Ürünlerimiz {
            get {
                return ResourceManager.GetString("Ürünlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Kılavuzu.
        /// </summary>
        public static string UserGuide {
            get {
                return ResourceManager.GetString("UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garanti Belgesi.
        /// </summary>
        public static string WarrantyCertificate {
            get {
                return ResourceManager.GetString("WarrantyCertificate", resourceCulture);
            }
        }
    }
}
